### ISSUE TITLE
Re: YouTube Vanced discussion. 

### ISSUE THREAD

**Issue by cheperth** [fembyfox/fembyfox.github.io#1]
The American First Amendment that allows free speech was inspired by the idea that free speech is a God given right that comes from God. The literal God that people pray to. This Idea predates the United States constitution and predates the United States constitution. Free speech wasn't magically created by the First Amendment. The First Amendment comes from the an idea of free speech that already existed. Free speech is a philosophy that millions of people believe in and practice. 

I am well aware that private companies are not bound to the first amendment. That is very obvious. That's why I suggested that YouTube Vanced or another open source app could have its own separate comment section as a way to circumvent YouTubes moderation practices. I never suggested any private company be forced to abide by The First Amendment. 

Here is a quote from Barack Obama telling college students to embrace free speech. 

“[We] have these values of free speech. And it’s not free speech in the abstract. The purpose of that kind of free speech is to make sure that we are forced to use argument and reason and words in making our democracy work. And, you know, you don’t have to be fearful of somebody spouting bad ideas. Just out-argue them. Beat ’em. Make the case as to why they’re wrong. Win over adherents. That’s how things work in a democracy.” - Barack Obama 

https://www.thefire.org/president-obama-student-protests-should-embrace-free-speech/

Students are private citizens. They are not bound by the free speech. I guess Barack Obama is a Conservative idiot.

**Comment by fembyfox** [comment]
This issue has nothing to do with my website and is trolling in nature and has been reported as such and will now be closed
